import type { IconType } from "react-icons";
import {
  LuAsterisk,
  LuCornerDownLeft,
  LuGlobe,
  LuLock,
  LuUser,
} from "react-icons/lu";

export const VARIABLE_SCOPES = [
  "all",
  "workspace",
  "captured",
  "secret",
  "personal",
] as const;

export type VariableScope = (typeof VARIABLE_SCOPES)[number];

export interface VariableScopeMeta {
  id: VariableScope;
  /** Human label rendered in the sidebar row. */
  label: string;
  /** Lucide icon component (canvas: scope glyph). */
  icon: IconType;
  /** Tooltip-style hint. */
  hint: string;
}

export const VARIABLE_SCOPE_META: Record<VariableScope, VariableScopeMeta> = {
  all: {
    id: "all",
    label: "All",
    icon: LuAsterisk,
    hint: "Every variable in the vault.",
  },
  workspace: {
    id: "workspace",
    label: "Workspace",
    icon: LuGlobe,
    hint: "Defined in envs/*.toml — versioned with the vault.",
  },
  captured: {
    id: "captured",
    label: "Captured",
    icon: LuCornerDownLeft,
    hint: "Generated by blocks (`{{alias.body.x}}`) during executions.",
  },
  secret: {
    id: "secret",
    label: "Secrets",
    icon: LuLock,
    hint: "Value lives in the keychain — never in a file.",
  },
  personal: {
    id: "personal",
    label: "Personal",
    icon: LuUser,
    hint: "Your account — stays on this machine.",
  },
};

/** Resolution chain rendered as the list-panel subtitle. */
export const VAR_RESOLUTION_HINT =
  "resolution: block → env → workspace → secret";

/** Helpers panel shown below the scopes in the sidebar. */
export const VARIABLE_HELPERS: ReadonlyArray<{
  syntax: string;
  hint: string;
}> = [
  { syntax: "{{uuid()}}", hint: "Fresh UUID v4 on every call" },
  { syntax: "{{now()}}", hint: "ISO-8601 of the execution moment" },
  { syntax: "{{base64(x)}}", hint: "base64 of x" },
  { syntax: "{{$prev.body.id}}", hint: "Capture from the block right above" },
];
