//! Keypress-decoded `Action` set. Input profiles (standard, vim)
//! decode raw keystrokes into this enum; `vim::dispatch` interprets
//! it against the app.

use crate::input::types::{
    InsertPos, Motion, Operator, PastePos, ScrollPos, TextObject, WindowCmd,
};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Action {
    Motion(Motion, usize),
    EnterInsert(InsertPos),
    InsertChar(char),
    InsertNewline,
    DeleteBackward,
    DeleteForward,
    ExitInsert,
    EnterCmdline,
    CmdlineChar(char),
    CmdlineBackspace,
    CmdlineDelete,
    CmdlineCursorLeft,
    CmdlineCursorRight,
    CmdlineCursorHome,
    CmdlineCursorEnd,
    CmdlineExecute,
    CmdlineCancel,
    OperatorMotion(Operator, Motion, usize),
    OperatorLinewise(Operator, usize),
    OperatorTextObject(Operator, TextObject, usize),
    Paste(PastePos, usize),
    Undo,
    Redo,
    RepeatChange(usize),
    EnterSearch(bool),
    SearchChar(char),
    SearchBackspace,
    SearchDelete,
    SearchCursorLeft,
    SearchCursorRight,
    SearchCursorHome,
    SearchCursorEnd,
    SearchExecute,
    SearchCancel,
    SearchRepeat {
        reverse: bool,
    },
    EnterQuickOpen,
    QuickOpenChar(char),
    QuickOpenBackspace,
    QuickOpenDelete,
    QuickOpenCursorLeft,
    QuickOpenCursorRight,
    QuickOpenCursorHome,
    QuickOpenCursorEnd,
    QuickOpenSelectNext,
    QuickOpenSelectPrev,
    QuickOpenExecute,
    QuickOpenCancel,
    TreeToggle,
    GitPanelToggle,
    GitPanelChar(char),
    GitPanelBackspace,
    GitPanelDelete,
    GitPanelCursorLeft,
    GitPanelCursorRight,
    GitPanelCursorHome,
    GitPanelCursorEnd,
    /// Empty draft → prefill via [`crate::git::template::commit_template`].
    GitPanelCommit,
    GitPanelCancel,
    /// Push without upstream opens the [`Action::GitConfirmSetUpstream`] modal.
    GitPanelSync,
    GitConfirmSetUpstream,
    GitCancelSetUpstream,
    OpenGitBranchPicker,
    CloseGitBranchPicker,
    MoveGitBranchPickerCursor(i32),
    ConfirmGitBranchPicker,
    OpenGitLogPage,
    CloseGitLogPage,
    MoveGitLogPageCursor(i32),
    /// Scrolls the diff pane without changing the selected commit.
    ScrollGitLogDiff(i32),
    OpenGitConflictResolver,
    CloseGitConflictResolver,
    MoveGitConflictResolverFile(i32),
    ResolveGitConflict(crate::git::ConflictVersion),
    GitPanelShare,
    /// Auto-resets after a successful commit.
    GitPanelToggleAmend,
    FocusSwap,
    TreeSelectNext,
    TreeSelectPrev,
    TreeSelectFirst,
    TreeSelectLast,
    TreeActivate,
    TreeCollapse,
    TreeRefresh,
    TabNext,
    TabPrev,
    TabGoto(usize),
    Window(WindowCmd),
    TreeCreate,
    TreeRename,
    TreeDelete,
    TreePromptChar(char),
    TreePromptBackspace,
    TreePromptDelete,
    TreePromptCursorLeft,
    TreePromptCursorRight,
    TreePromptCursorHome,
    TreePromptCursorEnd,
    TreePromptExecute,
    TreePromptCancel,
    Quit,
    EnterVisual,
    EnterVisualLine,
    VisualOperator(Operator),
    VisualSwap,
    VisualSelectTextObject(TextObject),
    ExitVisual,
    VisualPaste,
    RunBlock,
    OpenDbRowDetail,
    CloseDbRowDetail,
    CopyDbRowDetailJson,
    CloseHttpResponseDetail,
    CopyHttpResponseBody,
    OpenConnectionPicker,
    ExplainBlock,
    CopyAsCurl,
    /// Persists via `display=` in the fence on the next save.
    CycleDisplayMode,
    OpenFenceEditAlias,
    FenceEditChar(char),
    FenceEditBackspace,
    FenceEditDelete,
    FenceEditCursorLeft,
    FenceEditCursorRight,
    FenceEditCursorHome,
    FenceEditCursorEnd,
    FenceEditConfirm,
    FenceEditCancel,
    CloseConnectionPicker,
    MoveConnectionPickerCursor(i32),
    ConfirmConnectionPicker,
    /// If the deleted connection was the block's current `connection=`,
    /// the block keeps its stale id (re-runs surface the missing-connection
    /// error). No confirm step — connection rows are configuration, not data.
    DeleteConnectionInPicker,
    CompletionNext,
    CompletionPrev,
    CompletionAccept,
    CompletionDismiss,
    ConfirmDbRun,
    CancelDbRun,
    OpenDbExportPicker,
    CloseDbExportPicker,
    MoveDbExportPickerCursor(i32),
    ConfirmDbExportPicker,
    OpenDbSettingsModal,
    CloseDbSettingsModal,
    ConfirmDbSettingsModal,
    DbSettingsFocusNext,
    DbSettingsFocusPrev,
    DbSettingsChar(char),
    DbSettingsBackspace,
    DbSettingsDelete,
    DbSettingsCursorLeft,
    DbSettingsCursorRight,
    DbSettingsCursorHome,
    DbSettingsCursorEnd,
    OpenBlockHistory,
    CloseBlockHistory,
    /// Clamps at the ends (no wrap — matches the connection picker's feel).
    MoveBlockHistoryCursor(i32),
    /// Lazy-rebuilds the FTS5 index on first open this session.
    OpenContentSearch,
    CloseContentSearch,
    ConfirmContentSearch,
    MoveContentSearchCursor(i32),
    ContentSearchChar(char),
    ContentSearchBackspace,
    ContentSearchDelete,
    ContentSearchCursorLeft,
    ContentSearchCursorRight,
    ContentSearchCursorHome,
    ContentSearchCursorEnd,
    OpenEnvironmentPicker,
    CloseEnvironmentPicker,
    MoveEnvironmentPickerCursor(i32),
    ConfirmEnvironmentPicker,
    OpenConnectionsPage,
    CloseConnectionsPage,
    MoveConnectionsPageCursor(i32),
    OpenConnectionForm,
    CloseConnectionForm,
    ConnectionFormFocusNext,
    ConnectionFormFocusPrev,
    /// Driver field uses `ConnectionFormCycleDriver`; readonly uses
    /// `ConnectionFormToggleReadonly`. Other fields take Char/Backspace/etc.
    ConnectionFormChar(char),
    ConnectionFormBackspace,
    ConnectionFormDelete,
    ConnectionFormCursorLeft,
    ConnectionFormCursorRight,
    ConnectionFormCursorHome,
    ConnectionFormCursorEnd,
    ConnectionFormCycleDriver(i32),
    ConnectionFormToggleReadonly,
    ConnectionFormSubmit,
    OpenConnectionEditForm,
    /// Writes into `App.session_overrides`; the underlying connection
    /// is never mutated.
    OpenSessionOverrideForm,
    ClearSessionOverride,
    TestSelectedConnection,
    OpenConnectionDeleteConfirm,
    ConfirmConnectionDelete,
    CancelConnectionDelete,
    OpenEnvsPage,
    CloseEnvsPage,
    EnvsPageFocusToggle,
    EnvsPageFocusEnvs,
    EnvsPageFocusVars,
    EnvsPageMoveEnvCursor(i32),
    EnvsPageMoveVarCursor(i32),
    EnvsPageActivateEnv,
    OpenEnvForm,
    OpenEnvEditForm,
    CloseEnvForm,
    EnvFormChar(char),
    EnvFormBackspace,
    EnvFormDelete,
    EnvFormCursorLeft,
    EnvFormCursorRight,
    EnvFormHome,
    EnvFormEnd,
    EnvFormSubmit,
    OpenVarForm,
    OpenVarEditForm,
    CloseVarForm,
    VarFormChar(char),
    VarFormBackspace,
    VarFormDelete,
    VarFormCursorLeft,
    VarFormCursorRight,
    VarFormHome,
    VarFormEnd,
    VarFormFocusNext,
    VarFormFocusPrev,
    VarFormToggleSecret,
    VarFormSubmit,
    OpenEnvDeleteConfirm,
    OpenVarDeleteConfirm,
    ConfirmEnvOrVarDelete,
    CancelEnvOrVarDelete,
    OpenEnvCloneForm,
    CloseEnvCloneForm,
    EnvCloneFormChar(char),
    EnvCloneFormBackspace,
    EnvCloneFormFocusToggle,
    EnvCloneFormMoveVarCursor(i32),
    EnvCloneFormToggleVar,
    EnvCloneFormToggleAll,
    EnvCloneFormSubmit,
    /// Modal-only — no conflict with vim count-prefix.
    ActivateEnvByIndex(usize),
    OpenHelp,
    JumpNextBlock,
    JumpPrevBlock,
    /// Looked up by alias (preferred) or `segment_idx` against
    /// `App.last_run_anchor` — cursor doesn't have to be on the block.
    RerunLastBlock,
    WriteFile,
    WriteAll,
    /// Restores only the anchor + linewise flag (not the moving end).
    ReselectVisual,
    ScrollCursorTo(ScrollPos),
    OpenBlockTemplatePicker,
    /// Standard-mode Backspace; handles segment-boundary crossing as
    /// plain text and demotes a block to `Prose` if its `raw` becomes
    /// unparseable.
    DeleteBackwardStandard,
    /// Prose inserts `/` and opens the block-template picker; inside a
    /// block or block result, inserts `/` literally.
    SlashKey,
    OpenTabPicker,
    CloseTabPicker,
    MoveTabPickerCursor(i32),
    ConfirmTabPicker,
    CloseBlockTemplatePicker,
    MoveBlockTemplatePickerCursor(i32),
    ConfirmBlockTemplatePicker,
    /// Seeds `App.standard.anchor` from the cursor on the first one.
    SelectExtend(Motion),
    ClearSelection,
    Copy,
    Cut,
    PasteSystem,
    /// Intercepted in [`crate::input::route::route`] BEFORE the
    /// per-profile branch, so this variant never reaches `apply_action`.
    /// Exists so the inspectable keymap table in [`crate::input::map`]
    /// can name the binding without a parallel `MetaAction` enum.
    ToggleEditorMode,
    OpenVaultPicker,
    CloseVaultPicker,
    MoveVaultPickerCursor(i32),
    ConfirmVaultPicker,
    OpenVaultCreateForm,
    CloseVaultCreateForm,
    VaultCreateFormFocusNext,
    VaultCreateFormFocusPrev,
    VaultCreateFormChar(char),
    VaultCreateFormBackspace,
    VaultCreateFormSubmit,
    OpenVaultCloneForm,
    CloseVaultCloneForm,
    VaultCloneFormFocusNext,
    VaultCloneFormFocusPrev,
    VaultCloneFormChar(char),
    VaultCloneFormBackspace,
    VaultCloneFormSubmit,
    OpenVaultOpenPicker,
    CloseVaultOpenPicker,
    MoveVaultOpenPickerCursor(i32),
    /// Always descends (or ascends on `..`). Never opens as vault, so a
    /// vault-as-parent doesn't trap navigation. Use
    /// `VaultOpenPickerOpenAsVault` to open.
    VaultOpenPickerEnter,
    /// Opens the highlighted directory (Directory OR Vault) as the
    /// active vault via `switch_vault`. Allows a vault inside another.
    VaultOpenPickerOpenAsVault,
    VaultOpenPickerUp,
    CloseVaultMissingSecrets,
    MoveVaultMissingSecretsCursor(i32),
    VaultMissingSecretsEnterEdit,
    VaultMissingSecretsCancelEdit,
    VaultMissingSecretsChar(char),
    VaultMissingSecretsBackspace,
    VaultMissingSecretsSave,
    VaultMissingSecretsSkip,
    /// `Alt+,` contextual entry: routes to [`Action::OpenDbSettingsModal`]
    /// when the cursor sits on a DB/HTTP block (block-scoped
    /// limit/timeout), otherwise opens the app-wide Settings page.
    /// Same chord, two surfaces — mirrors `Tab`'s context-sensitive
    /// behaviour.
    OpenSettings,
    CloseSettingsPage,
    SettingsNextSection,
    SettingsPrevSection,
    SettingsMoveCursor(i32),
    /// Activate the row under the cursor. Section-dispatched by the
    /// applier: Keymaps → enter rebind capture; Theme → apply the
    /// highlighted preset.
    SettingsActivateRow,
    /// Abort an in-progress rebind without committing.
    SettingsCancelCapture,
    /// Key the user pressed while in capture mode. Applier converts
    /// to a chord string, writes config, persists.
    SettingsCommitCapture(crossterm::event::KeyEvent),
    /// Restore the row under the cursor to its built-in default.
    SettingsResetBinding,
    OpenBlocksView,
    CloseBlocksView,
    BlocksViewNextRegion,
    BlocksViewPrevRegion,
    /// Region index is 1-based to match the `Alt+1..N` chord; the
    /// applier converts to 0-based and clamps to the block kind's
    /// region count.
    BlocksViewJumpRegion(usize),
    Noop,
}
